apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mysql-template-instance
  namespace: default
  annotations:
    template-version: 1.1.7
    tested-operator-version: 4.1.3.2
spec:
  template:
    metadata:
      name: mysql-template
    parameters:
    - name: APP_NAME
      value: mysql-sample-app
    - name: DB_STORAGE
      value: "10Gi"
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: MYSQL_USER
      value: root1
    - name: MYSQL_PASSWORD
      value: tmax@23
    - name: MYSQL_DATABASE
      value: root1
