apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-user
  labels:
    purpose: namespace-user
    madeby: tmax
rules:
- apiGroups: ['']
  resources: ['namespaces']
  verbs: ['get','list']