apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: nginx-instance
  namespace: hypercloud-system
spec:
  clusterServiceClassName: nginx-template
  clusterServicePlanName: example-plan1
  parameters:
    NAME: nginx
    IMAGE: nginx:1
