apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mariadb-template-instance
  namespace: default
  annotations:
    template-version: 1.0.1
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: mariadb-template
    parameters:
    - name: APP_NAME
      value: mariadb-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "10Gi"
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: MYSQL_USER
      value: root1
    - name: MYSQL_PASSWORD
      value: tmax@23
    - name: MYSQL_DATABASE
      value: root1
