apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rolebindingclaims.tmax.io
  annotations:
    operator.version: 4.1.8.7
spec:
  group: tmax.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: rolebindingclaims
    singular: rolebindingclaim
    kind: RoleBindingClaim
    shortNames:
    - rbc
  preserveUnknownFields: true
  validation:
    openAPIV3Schema:
        # Users use rolebindingclaim to request rolebinding.
        # subject and roleRef of rolebindingclaim is the same as rolebinding.
        # Admins or Owner can change the 'status' of the rolebindingclaim.
        # If change the Status to 'Success', rolebinding is created.
        type: object
        required: [resourceName,apiVersion,kind,metadata,subjects,roleRef]
        properties:
          operatorStartTime:
            type: string
          resourceName:
            type: string
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
          subjects:
            # Equal RoleBinding Subjects Spec
            type: array
            items:
              type: object
              required: [kind,name]
              properties:
                kind:
                  type: string
                name:
                  type: string
                apiGroup:
                  type: string
          roleRef:
            # Equal RoleBinding roleRef Spec
            type: object
            required: [kind,name,apiGroup]
            properties:
              kind:
                type: string
              name:
                type: string
              apiGroup:
                type: string
          status:
            type: object
            properties:
              lastTransitionTime:
                format: date-time
                type: string
              message:
                type: string
              reason:
                type: string
              status:
                type: string
                enum:
                  - Awaiting
                  - Success
                  - Reject
                  - Error
  additionalPrinterColumns:
  - name: ResourceName
    type: string
    JSONPath: .resourceName
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Reason
    type: string
    JSONPath: .status.reason
  subresources:
    status: {}