apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: mysql-ha-template-instance
  namespace: default
  annotations:
    template-version: 1.1.6
    tested-operator-version: 4.1.3.2
spec:
  template:
    metadata:
      name: mysql-ha-template
    parameters:
    - name: APP_NAME
      value: mysql-ha-test-deploy
    - name: REPLICA
      value: 4

