apiVersion: tmax.io/v1
kind: Template
metadata:
  name: example-template
  namespace: default
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: example
    labels:
      app: example
  spec:
    selector:
      matchLabels:
        app: example
    template:
      metadata:
        labels:
          app: example
      spec:
        containers:
        - name: example
          image: example/image:version
          ports:
          - name: example
            containerPort: 80
 
