apiVersion: v1
kind: Pod
metadata:
  name: tmax-pod
  namespace: hypercloud-system
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: 172.22.6.2:31335/tomcat:8.5
    resources:
      limits:
        cpu: "200m"
        memory: "1Gi"
  imagePullSecrets:
  - name: hpcd-registry-tmax-registry
