apiVersion: tmax.io/v1
kind: Template
metadata:
  name: nodejs-mysql-template
  namespace: default
imageUrl: https://i.imgur.com/ImDhuQF.png
provider: tmax
recommend: false
shortDescription: NodeJS & MySQL Template
longDescription: NodeJS & MySQL Template
tags:
- was
- nodejs
- db
- mysql
plans:
- bindable: false
  description: nodejs-mysql
  name: nodejs-mysql-plan1
  schemas:
    service_instance:
      create:
        parameters:
          NAMESPACE: default
          DB_STORAGE: 5Gi
          APP_NAME: mysql-deploy
          MYSQL_USER: root1
          MYSQL_PASSWORD: tmax@23
          MYSQL_DATABASE: root1
parameters:
- name: APP_NAME
  displayName: PipelineName
  description: Pipeline name
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Application namespace
  required: true
- name: DB_STORAGE
  displayName: DBStorage
  description: Storage size for DB
  required: true
- name: MYSQL_USER
  displayName: MysqlUser
  description: MysqlUser
  required: true
- name: MYSQL_PASSWORD
  displayName: MysqlPassword
  description: MysqlPassword
  required: true
- name: MYSQL_DATABASE
  displayName: MysqlDatabase
  description: MysqlDatabase
  required: true
- name: GIT_URL
  displayName: GitURL
  description: Git Repo. URL
  required: true
- name: GIT_REV
  displayName: GitRev
  description: GitRevision
  required: true
- name: IMAGE_URL
  displayName: ImageURL
  description: Output Image URL
  required: true
- name: REGISTRY_SECRET
  displayName: RegistrySecret
  description: Secret for accessing image registry
  required: false
  value: ''
- name: REGISTRY_ID
  displayName: RegistryId
  description: ID for accessing image registry
  required: false
  value: ''
- name: REGISTRY_PW
  displayName: RegistryPw
  description: PW for accessing image registry
  required: false
  value: ''
- name: SERVICE_ACCOUNT_NAME
  displayName: serviceAccountName
  description: Service Account Name
  required: true
- name: WAS_PORT
  displayName: wasPort
  description: WAS Port
  valueType: number
  required: true
- name: DB_SERVICE_TYPE
  displayName: DbServiceType
  description: DB Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
- name: WAS_SERVICE_TYPE
  displayName: WasServiceType
  description: WAS Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
- name: PACKAGE_SERVER_URL
  displayName: PackageServerUrl
  description: URL (including protocol, ip, port, and path) of private package server
    (e.g., devpi, pypi, verdaccio, ...)
  required: false
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    type: ${WAS_SERVICE_TYPE}
    ports:
    - port: ${WAS_PORT}
    selector:
      app: ${APP_NAME}
      tier: nodejs
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-db-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    type: ${DB_SERVICE_TYPE}
    ports:
    - port: 3306
    selector:
      app: ${APP_NAME}
      tier: mysql
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-db-pvc
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    storageClassName: csi-cephfs-sc
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${DB_STORAGE}
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${APP_NAME}-secret
    namespace: ${NAMESPACE}
  type: Opaque
  stringData:
    user: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    database: ${MYSQL_DATABASE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}-mysql
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    selector:
      matchLabels:
        app: ${APP_NAME}
        tier: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          tier: mysql
      spec:
        initContainers:
        - name: init-privilege-${MYSQL_USER}
          image: busybox
          command:
          - sh
          - -c
          - echo 'mysql $mysql_flags -e "grant all privileges on *.* to ${MYSQL_USER}@'\''%'\''; flush privileges;"' >> /opt/app-root/src/mysql-init/privilege.sh
          volumeMounts:
          - name: mysql-init-cfg
            mountPath: /opt/app-root/src/mysql-init
        containers:
        - image: 192.168.6.110:5000/centos/mysql:5.7
          name: mysql
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: ${APP_NAME}-secret
                key: database
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql/data
          - name: mysql-init-cfg
            mountPath: /opt/app-root/src/mysql-init
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            exec:
              command:
              - /bin/bash
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: ${APP_NAME}-db-pvc
        - name: mysql-init-cfg
          emptyDir: {}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}-deploy-cfg
    namespace: ${NAMESPACE}
  data:
    deploy-spec.yaml: |
      spec:
        selector:
          matchLabels:
            app: ${APP_NAME}
            tier: nodejs
        template:
          metadata:
            labels:
              app: ${APP_NAME}
              tier: nodejs
          spec:
            imagePullSecrets:
            - name: ${REGISTRY_SECRET}
            containers:
            - env:
              - name: DB_HOST
                value: ${APP_NAME}-db-service
              - name: DB_PORT
                value: "3306"
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                    name: ${APP_NAME}-secret
                    key: user
              - name: DB_PW
                valueFrom:
                  secretKeyRef:
                    name: ${APP_NAME}-secret
                    key: password
              - name: DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: ${APP_NAME}-secret
                    key: database
              ports:
              - containerPort: ${WAS_PORT}
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: ${APP_NAME}-input-git
    namespace: ${NAMESPACE}
  spec:
    type: git
    params:
    - name: revision
      value: ${GIT_REV}
    - name: url
      value: ${GIT_URL}
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: ${APP_NAME}-output-image
    namespace: ${NAMESPACE}
  spec:
    type: image
    params:
    - name: url
      value: ${IMAGE_URL}
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: ${APP_NAME}-pipeline
    namespace: ${NAMESPACE}
  spec:
    resources:
    - name: source-repo
      type: git
    - name: image
      type: image
    params:
    - name: app-name
      type: string
      description: Application name
    - name: replica
      type: string
      description: Number of replica
      default: "1"
    - name: port
      type: string
      description: Application port
      default: "8080"
    - name: deploy-cfg-name
      description: Configmap name for description
    tasks:
    - name: build-source
      taskRef:
        name: s2i
        kind: ClusterTask
      params:
      - name: BUILDER_IMAGE
        value: 192.168.6.110:5000/s2i-nodejs:12
      - name: PACKAGE_SERVER_URL
        value: ${PACKAGE_SERVER_URL}
      - name: REGISTRY_ID
        value: ${REGISTRY_ID}
      - name: REGISTRY_PW
        value: ${REGISTRY_PW}
      resources:
        inputs:
        - name: source
          resource: source-repo
        outputs:
        - name: image
          resource: image
    - name: scan-and-sign-image
      taskRef:
        name: analyze-image-vulnerabilities
        kind: ClusterTask
      resources:
        inputs:
        - name: scanned-image
          resource: image
          from:
          - build-source
      params:
      - name: image-url
        value: $(tasks.build-source.results.image-url)
    - name: deploy
      taskRef:
        name: generate-and-deploy-using-kubectl
        kind: ClusterTask
      runAfter:
      - scan-and-sign-image
      resources:
        inputs:
        - name: image
          resource: image
      params:
      - name: app-name
        value: $(params.app-name)
      - name: replica
        value: $(params.replica)
      - name: port
        value: $(params.port)
      - name: image-url
        value: $(tasks.build-source.results.image-url)
      - name: deploy-cfg-name
        value: $(params.deploy-cfg-name)
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    generateName: ${APP_NAME}-run-
    namespace: ${NAMESPACE}
  spec:
    serviceAccountName: ${SERVICE_ACCOUNT_NAME}
    pipelineRef:
      name: ${APP_NAME}-pipeline
    resources:
    - name: source-repo
      resourceRef:
        name: ${APP_NAME}-input-git
    - name: image
      resourceRef:
        name: ${APP_NAME}-output-image
    params:
    - name: app-name
      value: ${APP_NAME}
    - name: replica
      value: "1"
    - name: deploy-cfg-name
      value: ${APP_NAME}-deploy-cfg

