apiVersion: tmax.io/v1
kind: TemplateInstance
metadata:
  name: redis-template-instance
  namespace: default
  annotations:
    template-version: 1.0.0
    tested-operator-version: 4.1.0.23
spec:
  template:
    metadata:
      name: redis-template
    parameters:
    - name: APP_NAME
      value: redis-sample-app
    - name: NAMESPACE
      description: A Namespace Name
      value: default
    - name: DB_STORAGE
      value: "10Gi"
    - name: SERVICE_TYPE
      value: ClusterIP
    - name: DATABASE_SERVICE_NAME
      value: redis
    - name: REDIS_PASSWORD
      value: tmax@23
