apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
kind: ClusterRoleBinding
metadata:
  name: admin
subjects:
- kind: User
  name: admin-tmax.co.kr # Name is case sensitive
roleRef:
  kind: ClusterRole  #this must be Role or ClusterRole
  name: cluster-admin  # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
