apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: namespaceclaims.tmax.io
  annotations:
    operator.version: 4.1.9.10
spec:
  group: tmax.io
  versions:
  - name: v1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: namespaceclaims
    singular: namespaceclaim
    kind: NamespaceClaim
    shortNames:
    - nsc
  preserveUnknownFields: true
  validation:
    openAPIV3Schema:
        # Users use namespaceclaim to request namespace and quotas.
        # The spec of namespaceclaim is the same as resourcequota.
        # Admins can change the 'status' of the namespaceclaim.
        # If Admin change the Status to 'Success', a namespace and resourcequota are created.
        # For Trial Type NameSpaceClaim, Add label 'trial: t'
        # For Trial Type NameSpaceClaim, Add label 'owner: "userId"'
        type: object
        required: [resourceName,apiVersion,kind,metadata,spec]
        properties:
          operatorStartTime:
            type: string
          resourceName:
            type: string
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
          spec:
            # Equal Resource Quota Spec
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required: [hard]
            properties:
              hard:
                type: object
                x-kubernetes-preserve-unknown-fields: true
                required: [limits.cpu,limits.memory]
                properties:
                  limits.cpu:
                    x-kubernetes-int-or-string: true
                  limits.memory:
                    x-kubernetes-int-or-string: true
          status:
            type: object
            properties:
              lastTransitionTime:
                format: date-time
                type: string
              message:
                type: string
              reason:
                type: string
              status:
                type: string
                enum:
                  - Awaiting
                  - Success
                  - Reject
                  - Error
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Reason
    type: string
    JSONPath: .status.reason
  subresources:
    status: {}