apiVersion: tmax.io/v1
kind: Template
metadata:
  name: wildfly-cicd-template
  namespace: default
imageUrl: https://upload.wikimedia.org/wikipedia/commons/a/a3/Wildfly_logo.png
provider: tmax
recommend: false
shortDescription: Wildfly CI/CD Template
longDescription: Wildfly CI/CD Template
tags:
- was
- wildfly
plans:
- bindable: false
  description: wildfly
  name: wildfly-plan1
parameters:
- name: APP_NAME
  displayName: AppName
  description: Application name
  required: true
- name: NAMESPACE
  displayName: Namespace
  description: Application namespace
  required: true
- name: GIT_URL
  displayName: GitURL
  description: Git Repo. URL
  required: true
- name: GIT_REV
  displayName: GitRev
  description: Git Revision
  required: true
- name: IMAGE_URL
  displayName: ImageURL
  description: Output Image URL
  required: true
- name: SERVICE_ACCOUNT_NAME
  displayName: serviceAccountName
  description: Service Account Name
  required: true
- name: WAS_PORT
  displayName: wasPort
  description: WAS Port
  valueType: number
  required: true
- name: SERVICE_TYPE
  displayName: ServiceType
  description: Service Type (ClsuterIP/NodePort/LoadBalancer)
  required: true
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}-service
    namespace: ${NAMESPACE}
    labels:
      app: ${APP_NAME}
  spec:
    type: ${SERVICE_TYPE}
    ports:
    - port: ${WAS_PORT}
    selector:
      app: ${APP_NAME}
      tier: was
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${APP_NAME}-deploy-cfg
    namespace: ${NAMESPACE}
  data:
    deploy-spec.yaml: |
      spec:
        selector:
          matchLabels:
            app: ${APP_NAME}
            tier: was
        template:
          metadata:
            labels:
              app: ${APP_NAME}
              tier: was
          spec:
            containers:
            - ports:
              - containerPort: ${WAS_PORT}
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: ${APP_NAME}-input-git
    namespace: ${NAMESPACE}
  spec:
    type: git
    params:
    - name: revision
      value: ${GIT_REV}
    - name: url
      value: ${GIT_URL}
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: ${APP_NAME}-output-image
    namespace: ${NAMESPACE}
  spec:
    type: image
    params:
    - name: url
      value: ${IMAGE_URL}
- apiVersion: tekton.dev/v1alpha1
  kind: Pipeline
  metadata:
    name: ${APP_NAME}-pipeline
    namespace: ${NAMESPACE}
  spec:
    resources:
    - name: source-repo
      type: git
    - name: image
      type: image
    params:
    - name: app-name
      type: string
      description: Application name
    - name: replica
      type: string
      description: Number of replica
      default: "1"
    - name: port
      type: string
      description: Application port
      default: "8080"
    - name: deploy-cfg-name
      description: Configmap name for description
    tasks:
    - name: build-source
      taskRef:
        name: s2i
        kind: ClusterTask
      params:
      - name: BUILDER_IMAGE
        value: 192.168.6.110:5000/s2i-wildfly:latest
      resources:
        inputs:
        - name: source
          resource: source-repo
        outputs:
        - name: image
          resource: image
    - name: scan-and-sign-image
      taskRef:
        name: analyze-image-vulnerabilities
        kind: ClusterTask
      resources:
        inputs:
        - name: scanned-image
          resource: image
          from:
          - build-source
      params:
      - name: image-url
        value: $(tasks.build-source.results.image-url)
    - name: deploy
      taskRef:
        name: generate-and-deploy-using-kubectl
        kind: ClusterTask
      runAfter:
      - scan-and-sign-image
      resources:
        inputs:
        - name: image
          resource: image
      params:
      - name: app-name
        value: $(params.app-name)
      - name: replica
        value: $(params.replica)
      - name: port
        value: $(params.port)
      - name: image-url
        value: $(tasks.build-source.results.image-url)
      - name: deploy-cfg-name
        value: $(params.deploy-cfg-name)
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineRun
  metadata:
    generateName: ${APP_NAME}-pipeline-run-
    namespace: ${NAMESPACE}
  spec:
    serviceAccountName: ${SERVICE_ACCOUNT_NAME}
    pipelineRef:
      name: ${APP_NAME}-pipeline
    resources:
    - name: source-repo
      resourceRef:
        name: ${APP_NAME}-input-git
    - name: image
      resourceRef:
        name: ${APP_NAME}-output-image
    params:
    - name: app-name
      value: ${APP_NAME}
    - name: deploy-cfg-name
      value: ${APP_NAME}-deploy-cfg
