apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: tokens.tmax.io
  annotations:
    operator.version: 4.1.9.9
spec:
  group: tmax.io
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: tokens
    singular: token
    kind: Token
    shortNames:
    - token
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:     
        type: object
        required: [accessToken, refreshToken]
        description: Token contains encrypted access token and refresh token
        properties:
          accessToken:
            type: string
          refreshToken:
            type: string